name: test_python

on:
  push:
    branches-ignore:
      - main

jobs:
  test_python:

    name: test_python
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: load pip cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt', 'requirements_dev.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-

      - name: install pip deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_dev.txt --upgrade

      - name: run tests
        run: py.test tests
