name: test_python

on:
  push:
    branches-ignore:
      - main

jobs:
  test_python:

    name: test_python
    runs-on: ubuntu-latest
    container: python:3.8-alpine

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: password123
          POSTGRES_USER: simple_messenger_user
          POSTGRES_DB: simple_messenger
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: load pip cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt', 'requirements_dev.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-

      - name: install pip deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_dev.txt --upgrade

      - name: run tests
        run: py.test tests
        env:
          SQLALCHEMY_DATABASE_URL: postgresql://simple_messenger_user:password123@postgres:5432/simple_messenger
